FROM node:22.14.0-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3002

CMD ["pnpm", "run", "dev", "--hostname", "0.0.0.0", "--port", "3002"]
