services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: snipr-backend
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
      
  postgres:
    image: postgres:16-alpine
    container_name: snipr-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
