services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: snipr-backend
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
